### ISSUE TITLE
[new addon] broadlink-adapter

### ISSUE THREAD

**Issue by sogaani** [mozilla-iot/addon-list#20]
Can you add an addon that I created?
[Here](https://github.com/sogaani/broadlink-adapter) is some infomation for this addon.

```
  {
    "name": "broadlink-adapter",
    "display_name": "Broadlink",
    "description": "Support ir devices with broadlink",
    "version": "0.1.0",
    "url": "https://github.com/sogaani/broadlink-adapter/releases/download/0.1.0/broadlink-adapter-0.1.0.tgz",
    "api": {
      "min": 1,
      "max": 1
    }
  }
```

**Comment by andrenatal** [comment]
Great work @sogaani !

Question: would this addon work with this blaster: http://amzn.to/2EF4Dft ? 

If not, with which blaster you tested it?

Thanks!

**Comment by sogaani** [comment]
Yes, I tested with this blaster: http://amzn.to/2EF4Dft .

My add-on work with a node module forked from [broadlinkjs-rm](https://github.com/lprhodes/broadlinkjs-rm).

I noticed that new blaster are being supported recently. It seems necessary to update the node  module to use the new blaster(rm3 pro plus).

I will update the node module, before putting addon on the list.

**Comment by sogaani** [comment]
now support this blaster: http://www.amazon.com/dp/B0753CDY86

But i tested with only http://amzn.to/2EF4Dft

```
  {
    "name": "broadlink-adapter",
    "display_name": "Broadlink",
    "description": "Support ir devices with broadlink",
    "version": "0.1.1",
    "url": "https://github.com/sogaani/broadlink-adapter/releases/download/0.1.1/broadlink-adapter-0.1.1.tgz",
    "api": {
      "min": 1,
      "max": 1
    }
  }
```

**Comment by andrenatal** [comment]
@sogaani  I got the broadlink adapter and have it working with their app. In the gateway I managed to install the addon and can see both BroadlinkManager and BroadlinkAdapter adapters running, but when I press the + button on the things page, the device isn’t found. Is there something else that should be done to make the gateway find the device?

**Comment by sogaani** [comment]
I do not know if there is a way to refer to the setting of broadlink mobile app.
If the addon configuration UI is added to the gateway, it will be able to configure adding ir devices from the gateway.
Currently, I only support how to add IR devices from addon config like gpio adapter.

For example, the following configuration would have light.
```
{
    "devices": [
        {
            "mac": "34:ea:34:c7:b2:ec",
            "type": "light",
            "id": "Light0",
            "name": "Living Light",
            "ir": {
                "on": "26005000000124911311141114111411141114111411143513111435133513351311143513351311143513111411141114351311141114111411143513351335131114351335133513000d05",
                "off": "26005000000124911311141114111411141114111411143513111435133513351311143513351311141114111411141114111411141114111435133513351335133513351335133513000d05"
            }
        }
    ]
}
```

It is hard to write JSON as above, I push a command line tool for creating config, so I upgrade addon tonight.

These information are written in [Readme](https://github.com/sogaani/broadlink-adapter), but should I write on the gateway wiki?

thanks!

**Comment by mrstegeman** [comment]
No, I think your README is the right place for now.

Just a reminder that if you update your add-on, you need to submit a new PR/issue to the addon-list repo.

**Comment by andrenatal** [comment]
These IR codes are in the same format of the ones captured using Lirc,
right?

If yes, would be a good idea to explain in the Readme how the user can
capture these codes using a receiver to then input in the json, but I agree
that the best solution would be to add a configuration ui in the gateway.

The question is: does the broadlink expose a recording API as well? I mean,
some method the addon would call to put it in recording mode, and when the
user presses the keys he wants to record on his remote, the device sends
back these codes to the addon who finally writes them into the json.

I think that would be a more appropriate UX. I don't know how the Alexa
integration with broadlink works. Would be interesting to understand if
they do something similar to handle the recordings.

**Comment by sogaani** [comment]
Thank you for your feedback.

> The question is: does the broadlink expose a recording API as well?

I know how to use recording API. The command line tool attached to the add-on version 0.1.2 records the IR code and outputs it with JSON.

I will update the README for more clarity.

**Comment by sogaani** [comment]
hi.

I want update addon.

```
  {
    "name": "broadlink-adapter",
    "display_name": "Broadlink",
    "description": "Support ir devices with broadlink. Need configuration, See: https://github.com/sogaani/broadlink-adapter",
    "version": "0.1.3",
    "url": "https://github.com/sogaani/broadlink-adapter/releases/download/0.1.3/broadlink-adapter-0.1.3.tgz",
    "checksum": "501650e26e6b434f0ef60de4cacc286e193c4d98e8ccc13e977e681bbb7def84",
    "packages": {
      "any": {
        "url": "https://github.com/sogaani/broadlink-adapter/releases/download/0.1.3/broadlink-adapter-0.1.3.tgz",
        "checksum": "501650e26e6b434f0ef60de4cacc286e193c4d98e8ccc13e977e681bbb7def84"
      }
    },
    "api": {
      "min": 1,
      "max": 2
    }
  }
```

**Comment by mrstegeman** [comment]
Done (#32)

**Comment by joelafonso** [comment]
@sogaani I can not discover any broadlink devices. I do click on "+" but it doesn't discover any… Is there anything else i should do?

**Comment by mrstegeman** [comment]
@joelafonso Again, could you file a new issue to the add-on’s repository? It is not maintained by our team, but by an outside contributor. See link below:

https://github.com/sogaani/broadlink-adapter/issues
