### ISSUE TITLE
Have this list somewhere discoverable

### ISSUE THREAD

**Issue by sknebel** [mozilla-iot/addon-list#235]
I've been poking around a bit after seeing https://hacks.mozilla.org/2019/04/introducing-mozilla-webthings/ and this list seems like it'd provide a good starting point for "what actually exists/works already", if one could a) easily find it and b) read it without reading JSON.

**Comment by mrstegeman** [comment]
See:
* https://api.mozilla-iot.org:8443/addons/info
* https://github.com/mozilla-iot/wiki/wiki/Supported-Hardware

We're working on converging these two in [mozilla-iot/device-compat](https://github.com/mozilla-iot/device-compat).
