### ISSUE TITLE
[new add-on] MySensors adapter

### ISSUE THREAD

**Issue by createcandle** [mozilla-iot/addon-list#238]
The adapter is still in beta (as in: not all MySensors types are supported). But the only people who will be tempted to use it right now are used to that.

The MySensors forum now has a Mozilla Webthings Gateway section, and news of this adapter is the first post there:
https://forum.mysensors.org/topic/10342/mozilla-webthings-mysensors-add-on-adapter

Things I don't know or am unsure about:
- I don't know if this is the correct architecture. I generated this .tgz on a Raspberry Pi 3B that was running the Mozilla Gateway 0.7 image, upgraded tot 0.8.
- I don't know if this is the correct link for a file on Github.
- I don't know that Gateway API version I should choose, so I just left it at 2 and 2. It's the same in the package.json
- I've added some config and schema things to the package.json. I've never seen it show up as options in the interface though? In the future I would like to use those configuration options to let the user select what type of radio/connection to make. For now the serial option is a fine first default. I could remove that bit since it's not currently used yet.
- How do I know if my package uses binaries?

```
{
  "name": "mysensors-adapter",
  "display_name": "MySensors adapter",
  "description": "Build your own smart home with this Arduino library",
  "author": "CreateCandle",
  "homepage": "https://github.com/createcandle/Webthings-mysensors-adapter",
  "license": "https://github.com/createcandle/Webthings-mysensors-adapter/blob/master/LICENSE",
  "packages": [
    {
      "architecture": "linux-arm",
      "language": {
        "name": "python",
        "versions": [
          "3.5", "3.6", "3.7"
        ]
      },
      "version": "0.0.1",
      "url": "https://github.com/createcandle/Webthings-mysensors-adapter/raw/master/mysensors-adapter-0.0.1.tgz",
      "checksum": "e04f99eb223e737ab2fd0205ee5363a794b128b1848b0bd1dd6b188d3f6758bf",
      "api": {
        "min": 2,
        "max": 2
      }
    }
  ]
}

**Comment by mrstegeman** [comment]
I submitted a PR with some fixes. Please merge those and build a new release.

**Comment by mrstegeman** [comment]
I typically just make a tag and upload the .tgz to the release.

**Comment by createcandle** [comment]
That new package.sh ran so fast I didn't realise it actually ran until I saw the .tgz file.

The new checksum is c73f7cb36ed95ca73c3836b195ddab2a4b69cacd61745f429e3278a31b4ef61a
