### ISSUE TITLE
[new add-on] Network presence detection

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/addon-list#241]
```json
{
  "name": "webthings-network-presence-detection",
  "display_name": "Network presence detector",
  "description": "Check if devices are on your network.",
  "author": "Flatsiedatsie",
  "homepage": "https://github.com/flatsiedatsie/webthings-network-presence-detection",
  "license": "https://github.com/flatsiedatsie/webthings-network-presence-detection/blob/master/LICENSE",
  "packages": [
    {
      "architecture": "linux-arm",
      "language": {
        "name": "python",
        "versions": [
          "3.5", "3.6", "3.7"
        ]
      },
      "version": "0.0.3",
      "url": "https://github.com/flatsiedatsie/webthings-network-presence-detection/raw/master/network-presence-detection-adapter-0.0.3.tgz",
      "checksum": "0e17166996fc9ec621c6782a72c55220994c00beda24da11a31668d81f28d6fc",
      "api": {
        "min": 2,
        "max": 2
      }
    }
  ]
}
```

**Comment by flatsiedatsie** [comment]
Ah you beat me to it :-) But because of the error because we were both editing it I lost the things I was trying to add. The short version:

There are no requirements. Is this correct? It uses:
```
import time
import threading
import subprocess
import json
import re
import os
```

**Comment by mrstegeman** [comment]
You're trying to import `mysensors` in some of the code. Should that be removed?

**Comment by flatsiedatsie** [comment]
Yes it should! I will fix it.

**Comment by flatsiedatsie** [comment]
Done. New SHA is f13c86dfea79acadffdf5f789fbc2f9a0d2bfcde7ef563b21e395f31218d140b

**Comment by flatsiedatsie** [comment]
If an add-on generates a JSON file itself on first-run, should that filename be added to the files list in package.json?

**Comment by mrstegeman** [comment]
I submitted a PR to your adapter, as well as a couple issues. I'll have one more PR after the first one is merged.

**Comment by flatsiedatsie** [comment]
I've committed the changes, and have fixed the wrong util file. Thanks for the help.

**Comment by flatsiedatsie** [comment]
The new tar file:
https://github.com/flatsiedatsie/webthings-network-presence-detection/raw/master/network-presence-detection-adapter-0.0.1.tgz

The new checksum:
1e70130ae78a99edb29c3ea2d6a1f6ea9e189fef93f3c15fc443cf3795c9bea3

**Comment by flatsiedatsie** [comment]
I had a look in the log and noticed:

```

2019-05-01 01:07:17.418 INFO   : Not checking SHA256SUMS file for mysensors-adapter since a .git directory was detected
2019-05-01 01:07:17.422 INFO   : Not checking SHA256SUMS file for network-presence-detection-adapter since a .git directory was detected

...


2019-05-01 01:07:28.046 INFO   : Not updating mysensors-adapter since a .git directory was detected
2019-05-01 01:07:28.048 INFO   : Not updating network-presence-detection-adapter since a .git directory was detected
```

**Comment by flatsiedatsie** [comment]
I've looked into it a bit more, and did some more tests.

ARP does not forget devices quickly enough, so is not useful as a form of presence detection.

Using SCAPY will solve that problem, and also improve the add-on's ability to find mobile mobile devices.

Scapy has a few downsides:
- It requires sudo to run. How would you feel about a module doing that? I tried to avoid it, but it seems necessary.
- On top of that it required a package to be installed: tcpdump. Ofherwise I got the error `scapy.error.Scapy_Exception: tcpdump is not available. Cannot use filter`. How would you feel about that requirement, and can add-ons even install things like this? 
- Installation on the Raspberry Pi currently does not work via 'pip3 install scapy'. There is a [small bug](https://github.com/secdev/scapy/issues/1864) where for now you have to do `pip3 install --pre scapy'. On my system I even had to do  `sudo pip3 install --pre scapy` before it finally could be imported in my test sketch.

Scapy also is user for nefarious purposes, like ARP spoofing, and might now be something you want to have installed on the device?

I'm looking into:
- Just installing arping and using that.
- some combination of simpler things that emulates the scanning ability but does not require escalation. But since it requires access to network layer two it may always need sudo of some kind.

Any advice?

**Comment by tim-hellhake** [comment]
Sounds a bit like an overkill, `arping` is exactly what you want.
However it will also need root rights.
Did you consider to use a combination of arp and ping?

**Comment by mrstegeman** [comment]
I think what you're going to end up with is the [Wake-on-LAN adapter](https://github.com/mozilla-iot/wake-on-lan-adapter), just without the "Wake" action. That adapter can already tell you if the devices are present or not by doing a combination of ARP lookups and pings.

**Comment by flatsiedatsie** [comment]
Thanks for the tips!

I've created version 0.0.2

https://github.com/flatsiedatsie/webthings-network-presence-detection/blob/master/network-presence-detection-adapter-0.0.2.tgz

c49f09a422d5f88841237b7fd63e3c7fbd406ef4014602562e53670d0e95ea87

- It now uses ping, arping and arp. Arping uses a sudo command. Arping can be disabled, but without it you lose the ability to track mobile phones accurately / at all.
- It now actually works :-) Arp didn't remove devices from the table after the left the network. Not nearly fast enough in any case.
- It's now multi threaded. I've capped it at 5 since there is no rush to scan everything.
- Devices have a new integer property: 'last seen X minutes ago'.

**Comment by mrstegeman** [comment]
Things still didn't work for me. I opened a new PR for you to look at.

**Comment by mrstegeman** [comment]
Also, there's no way to disable arping...

**Comment by raidnet-ms** [comment]
Relating devices to specified user would be useful for future implementation. This might be done from user setting perspective.

**Comment by mrstegeman** [comment]
https://github.com/flatsiedatsie/webthings-network-presence-detection/pull/5/files?w=1

**Comment by flatsiedatsie** [comment]
Sorry for being unclear: disabling arping is currently not a setting, I just meant that it would be possible to remove it if it was a show stopper. Then it would rely on ping only. Currently it tries to use ping first, and only if that fails will it try arping as a fall-back. That fall-back could be removed. It would cripple the add-on, but it would still work.

I accepted your changes and did a small test.
- The name of each device is now 'address'? The mac-address lookup doesn't work?
- Why was `arp -a` changed to just `arp`?

**Comment by flatsiedatsie** [comment]
It seems in the new code the mac_address as an ID is used in two ways now.
- As a pure mac-address stripped of all the `:`
- As the above but with 'presence-' in front of it.

I will make if the latter everywhere.

**Comment by flatsiedatsie** [comment]
I've updated to version 0.0.3.
I've updates the json in the first post.

I'm running some tests now.

**Comment by mrstegeman** [comment]
I added a `presence-` prefix to the device IDs to avoid possible conflicts with other add-ons.

Yes, I did switch back to `arp <ip>`, because `arp -a <ip>` doesn't work on macOS. The way you previously had it also failed to parse the macOS output properly, but you were also trying to get the full arp table, hence the need for `arp -a` at the time.

To answer your questions:
1. You can't require a system package. That's why I was hoping there was a native Python package that would do what you needed. Right now, on my Mac, I get lots of these errors, which is why I was hoping for a way do disable `arping` (this can be done in the future):
    `ERROR  : network-presence-detection: sudo: arping: command not found`
2. I think there was maybe a bad merge at some point. I opened one more PR to fix that issue. `bootstrap.py` is only needed if you're installing dependencies via `pip`.

**Comment by flatsiedatsie** [comment]
Thanks for the explanation, and of course very much for the help, I really appreciate it. 

Too bad requiring a system package is not possible, I'll explore ways around that, including making arping optional through a checkbox.

**Comment by mrstegeman** [comment]
No problem!

Things seem to work well now, so if you build a new release package, I'll get this released.

**Comment by flatsiedatsie** [comment]
I just did :-)

I quickly added a boolean checkbox for using arping. Testing now.

99b5e8ab89a4634f138227b6edc02df5856bc15c168c008e38b8782d5fc130cf

**Comment by flatsiedatsie** [comment]
Hmm, it's not showing up in the add-on list now. Will be able to fix it tomorrow.

**Comment by mrstegeman** [comment]
This fixes it: https://github.com/flatsiedatsie/webthings-network-presence-detection/pull/7

**Comment by flatsiedatsie** [comment]
Thanks!

It's done. 

I've set arping to be disabled by default. The json in the first post above has been updated.

**Comment by flatsiedatsie** [comment]
Ah I must have forgotten to update the package.json file on github.
