### ISSUE TITLE
[new addon] ESP adapter

### ISSUE THREAD

**Issue by fiz1962** [mozilla-iot/addon-list#25]
I've made an adapter than scans a range of IP addresses for devices that respond with a json "Thing" response at http://IPAddress/thing during pairing.  The devices found are configured with Properties from this response.  "ESP" refers to the initial device I targeted, the Wemos Mini (ESP8266).  I've included an example Arduino sketch and also PHP code that runs on an Apache web server.  If you would like to incude it, it is

  {
    "name": "ESP-adapter",
    "display_name": "ESP",
    "description": "Support any web device that can accept/respond with json data",
    "version": "0.3.0",
    "url": "https://github.com/fiz1962/ESP-adapter/archive/0.3.tar.gz",
    "api": {
      "min": 1,
      "max": 1
    }
  }

**Comment by mrstegeman** [comment]
I'd be happy to merge this in for you! First, you'll need to package this like an npm package.  You could use a script like this: https://github.com/mozilla-iot/virtual-things-adapter/blob/master/package.sh

**Comment by fiz1962** [comment]
Thanks, I think I got it packaged properly this time :)

{
"name": "ESP-adapter",
"display_name": "ESP",
"description": "Support any web device that can accept/respond with json data",
"version": "0.3.1",
"url": "https://github.com/fiz1962/ESP-adapter/blob/master/releases/esp-adapter-0.3.1.tgz",
"api": {
"min": 1,
"max": 1
}
}

**Comment by mrstegeman** [comment]
1 small issue. I submitted a PR for you: https://github.com/fiz1962/ESP-adapter/pull/1

**Comment by mrstegeman** [comment]
@fiz1962 could you address James' comment on the PR: https://github.com/mozilla-iot/addon-list/pull/26#issuecomment-368588291
