### ISSUE TITLE
Lifx addon

### ISSUE THREAD

**Issue by steveatinfincia** [mozilla-iot/addon-list#36]
Hi :)

I put together an Lifx smart bulb addon, available here:

https://github.com/infincia/lifx-adapter

Still needs some testing for color bulbs, and I haven't tested the color temperature stuff yet, but otherwise it is working well for my A19 bulb.

**Comment by steveatinfincia** [comment]
Ahh I just noticed `lifxlan` pulls in `netifaces`, which builds as a binary library.

The package I've released was built on a Pi Zero, so (as far as I know) it should still work on Pi 3, but obviously that's not a good way to go.

What would be a better way to handle addon dependencies that build binary libraries?

**Comment by mrstegeman** [comment]
@steveatinfincia I submitted a PR to your repo. If you pull that in and make a new release, I will add it to the list.

For the 0.3.X release, this will only work on the Raspberry Pi, so I can make a note of that in the description. For 0.4.X+, we'll have support for building packages for multiple architectures, so we can cross that bridge when we get to that point (or you can experiment with building multiple packages yourself). I'm actually dealing with `netifaces` in another add-on I'm working on as well.

**Comment by mrstegeman** [comment]
@steveatinfincia Let us know if/when you need your add-on updated in the list!
