### ISSUE TITLE
Add miLight-adapter-v0.0.5

### ISSUE THREAD

**Issue by atirage** [mozilla-iot/addon-list#635]
I would like to add my adapter for miLight WiFi controller and bulbs to the official add-on list:
https://github.com/atirage/miLight-adapter/releases/tag/v0.0.5.

Since my repo si not a fork of addon-list, I was not able to create a pull-request.

**Comment by mrstegeman** [comment]
I'd be happy to add that for you! I've opened a PR that I'd like you to merge first, and build a new release (or just rebuild your current one): https://github.com/atirage/miLight-adapter/pull/1

**Comment by atirage** [comment]
Thanks! I've merged the PR and rebuilt the release. I also made a quick check to make sure things are still working.

**Comment by mrstegeman** [comment]
Ok, two quick things:
1. Can you set the `homepage` in your `package.json` to: `"https://github.com/atirage/miLight-adapter#readme"`
2. Please run the `package.sh` script and attach the `.tgz` file to your release, as that's the file we actually need.

**Comment by atirage** [comment]
Done, I've rebuilt the release: https://github.com/atirage/miLight-adapter/releases/tag/v0.0.5

**Comment by mrstegeman** [comment]
Oops, `homepage_url` in `manifest.json` needs to be set as well.

**Comment by atirage** [comment]
No worries, I should've noticed that myself also. :)
Hope it's fine now: https://github.com/atirage/miLight-adapter/releases/tag/v0.0.5
