### ISSUE TITLE
Modbus RTU adapter

### ISSUE THREAD

**Issue by bademux** [mozilla-iot/addon-list#672]
Please add suport for standard modbus RTU (and ASCII) protocol.
A lot of sensors and gadgets handle  it.
Issue can be related to https://github.com/mozilla-iot/gateway/issues/1459, as both Modbus RTU and DMX512 use RS485

**Comment by tim-hellhake** [comment]
> Issue can be related to https://github.com/mozilla-iot/gateway/issues/1459, as both Modbus RTU and DMX512 use RS485

Unfortunately, this won't help with the DMX issue.
RS485 only defines the electrical characteristics.
The protocol is different.
