### ISSUE TITLE
zmote IR transmitter devices adapter

### ISSUE THREAD

**Issue by MagicFab** [mozilla-iot/addon-list#675]
I' d like to request adding support to [zmote](http://zmote.io/) IR transmitter devices:

* http://zmote.io/
* http://zmote.io/pro

This would bring control for many IR-devices in Mozilla WoT Gateway.

There is existing code and documentation that could probably be used for this:

* https://github.com/zmoteio
* [Rest control over zmote](https://hackaday.io/project/7858-zmote/log/27078-rest-control-over-zmote)
* https://github.com/alexmaret/openhab-binding-zmote
* [openHAB forums discussions about zmote](https://community.openhab.org/search?q=zmote)

**Comment by tim-hellhake** [comment]
resolved by #781

**Comment by MagicFab** [comment]
Can you add any details to this implementation ? Glad to see this made it into supported addons :)

**Comment by tim-hellhake** [comment]
@MagicFab
> Can you add any details to this implementation?

What do you mean by details?

> Glad to see this made it into supported addons :)

I wanted to do it earlier but the shipment took quite some time.
