### ISSUE TITLE
[Feature] Kafka client integration

### ISSUE THREAD

**Issue by vidursatija** [mozilla-iot/addon-list#831]
Hello Mozilla-IoT team,

I was thinking that having Kafka client integration in the gateway might be awesome. A Kafka client will allow the gateway to publish IoT data that later can be used for processing and storing.

I would love to contribute and have studied the gateway backend codebase fairly. I have some experience in using Kafka with Node.js.
With little guidance, I'll be able to make this idea into a feature.

How soon can I start with this?

**Comment by vidursatija** [comment]
@tim-hellhake let me know when you want me to test it.

Thank you so much for this addon!

**Comment by tim-hellhake** [comment]
@vidursatija
The kafka bridge is available in the addon list now.
